apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREE0TURVeApNVEV6TVRGYUZ3MDBOREE0TURVeE1URXpNVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQlU0VUNuL1FFRkNWaEl3cEdZQUdVRFk3bERKWXNsejZvSWEzSnRFTHBUY2ZWVjZDQQpmYTVmV3JySklLUVY4MXV6YkN0RmpkQlBqeWVuT1ltcE9ZWU81ZUxGTDhPcVJpa3JtdGhoSnlIREhIcGVua0hiCmFYWnlMV2s5dUZyK0YzbnZKZ2VJREQvdk9ZZUcyWlI4R1dMNm5OWndITVFOcUcrK09sbzIwbkhiNE00ZUQ5RXAKWTVKdjFBNjRybVBvMnV6VXVTMnlSOWxsM0ZaSWZlUk5MbGE0OE5MMFdjMnFMaFlHWUo4L0RIWFh0eFVRaG9kZwppMGJ0RDlYUjZWQmJ5TkRwbWFQSTJkU0FlQldJTTUxaHlubHpzK1R1eUpHQmJkd1FUUi9PRitGMmRXUUpDVnd1CmpGbDZ5M3Y2Z1JqUHBGUHIvdlBVOENwR01tY0sydm5zdnlQaEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFiQ0c4RFRGcmtoWERHYXpSTAoveXFTMzBDUzV6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGaExFaHdqc1dsRzN5dm94OC8rVTgyeU9OODBzCnVPZkRIUkFkMUpHNTc1aTlKL2VEVXNXS2RXenZOKytUTGdmQmxJb1phZGJrZ0tsYWY2YVl3UEFYOVZwbERDOE4KN2JqejhEaXV4bnAzRjZWS3B0VUVjbmFGeldKWVVXQjRNd0hzYU9pMWIwZ1kwRFlLdzdWU1BnZWdMS1h6V3BEYQp0cHJReGRhQ0FqRHJKSDV5Q3FxTEFlN2RRQURZeTc3UmpSUUluV1RYZjUrNXdIS1RyREplaVFnZHA3VWUzWjJ4Cm11d2t6L3RYZUlUKzYxSUFtaTZVNlF4RW01b2F6eTJuaGxVQ1psbUkzNTZ0elBrbVB5Y0ZURWtQcEJpVkJwN1kKYkdxU09FZzg5U2NnNStzRWZWZkpkUmVYOGs1OCtqUVMveGViT1dTYXRJaEF4Rm9uWVhMWlBObnliUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6ec9208c-f837-473c-a80a-07299df78697.k8s.ondigitalocean.com
  name: do-nyc3-tic-tac-toe-cluster
contexts:
- context:
    cluster: do-nyc3-tic-tac-toe-cluster
    user: do-nyc3-tic-tac-toe-cluster-admin
  name: do-nyc3-tic-tac-toe-cluster
current-context: do-nyc3-tic-tac-toe-cluster
users:
- name: do-nyc3-tic-tac-toe-cluster-admin
  user:
    token: dop_v1_d714c91123a834162c2832f26a04c05db1c0c2ccd90c8bb25b8d301c99e201c1
