name: Build,Analyze,scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: [Linux]  # Use a standard runner for better compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check SonarQube Server Connection
        run: |
          curl -I ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: '-X'

      - name: Build and analyze with Sonarqube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
