name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master  # Specify a stable version
        with:
          args: ''
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: npm install dependencies
        run: npm install

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
        continue-on-error: true

      - name: Trivy file scan
        run: trivy fs . > trivyfs.txt
        continue-on-error: true
     
      - name: Upload Trivy results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivyfs.txt

      - name: Docker build and push
        run: |
          docker build -t tic-tac-toe .
          docker tag tic-tac-toe bettergreat/tic-tac-toe:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push bettergreat/tic-tac-toe:latest

        env: 
          DOCKER_CLI_ACI: 1
          
      - name: Image Scan
        run: trivy image bettergreat/tic-tac-toe:latest > trivyimage.txt

  deploy:
    needs: build-analyze-scan
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
        continue-on-error: true 
        
      - name: docker pull image
        run: docker pull bettergreat/tic-tac-toe:latest

      - name: Image scan
        run: trivy image bettergreat/tic-tac-toe:latest > trivyimagedeploy.txt
      
      - name: Deploy to container
        run: docker run -d --name game -p 3000:3000 bettergreat/tic-tac-toe:latest
      
      - name: Update kubeconfig
        run: doctl kubernetes cluster kubeconfig save tic-tac-toe-cluster

      - name: Deploy to kubernetes
        run: kubectl apply -f deployment.yml service.yml

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-tic-tac-toe-game'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
